name: Java CI GeekHub project

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Setup build
        uses: gradle/gradle-build-action@v2

      - name: Execute gradle assemble
        run: ./gradlew assemble

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Setup gradle for tests
        uses: gradle/gradle-build-action@v2

      - name: Execute gradle test
        run: ./gradlew test

  checkstyle:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Setup gradle for checkstyle
        uses: gradle/gradle-build-action@v2

      - name: Execute gradle checkstyleMain
        run: ./gradlew checkstyleMain

      - name: Execute gradle checkstyleTest
        run: ./gradlew checkstyleTest
